#%RAML 1.0
title: Emanate Colaboration Contract
baseUri: https://casam2.ddns.net/
version: v1
description: |
  Make some description here...
protocols: [HTTP]
              
/propose:
    description: "Propose a collaboration contract to one or several users"
    post:
        description: "Propose a collaboration contract to one or several users"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser1", 
                        "name": "contract1", 
                        "price": 10000, 
                        "partners": [
                            {"name": "colabuser2", 
                            "percentage": 10}
                        ]
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }
              
/accept:
    description: "Accept a contract proposal"
    post:
        description: "Accept a contract proposal"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "contract1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

                            
                            
/reject:
    description: "Reject a contract proposal"
    post:
        description: "Reject a contract proposal"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "contract1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

                    
/execute:
    description: "Execute the contract"
    post:
        description: "Execute the contract"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "user1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

/getContract:
    description: "Get contract details"
    post:
        description: "Get contract details"
        body:
            application/json:
                example: | 
                    {
                        "proposer": "colabuser2", 
                        "contract": "contract1", 
                    }
